---
- name: Clone config file
  git: 
    repo: https://{{ github_user_name }}:{{ github_password }}@github.com/keisuke123/{{ config_repository_name }}.git
    dest: "{{ download_path }}/{{ config_repository_name }}"

- name: Copy config file
  synchronize:
    src: /tmp/{{ config_repository_name }}/config
    dest: /home/{{ user_name }}
  delegate_to: "{{ inventory_hostname }}"

- name: Add shimamon
  shell: | 
    if ! grep -q "shimamon" /home/{{ user_name }}/.bash_profile 2>/dev/null; then
      cat /home/{{ user_name }}/config/bash_profile >> /home/{{ user_name }}/.bash_profile;
    fi

- name: Load bash_profile
  shell: source /home/{{ user_name }}/.bash_profile executable=/bin/bash

- name: Move .vimrc
  shell: cp -f ~/config/vimrc ~/.vimrc

- name: Make backup directory
  file: 
    path: /home/{{ user_name }}/backup
    state: directory
    owner: "{{ user_name }}"
    mode: 0755

- name: Backup nginx files
  shell: |
    cp /etc/nginx/nginx.conf /home/{{ user_name }}/backup/nginx_`date "+%Y%m%d_%H%M%S".conf`

- name: Backup MySQL files
  shell: 
    cp /etc/mysql/my.cnf /home/{{ user_name }}/backup/my_`date "+%Y%m%d_%H%M%S".cnf`
    mysqldump --single-transaction -u ${  } -p --all-databases | gzip > /home/{{ user_name }}/backup/mysqldump_`date "+%Y%m%d_%H%M%S"`.gz

- name: Updates apt cache
  action: apt update_cache=tr

- name: Install python-apt
  apt: name=python-apt

- name: Install common packages and editors
  apt: name={{ item }} update_cache=yes
  with_items:
    - emacs
    - vim 
    - htop
    - unzip
  
- name: Get alp source
  get_url: 
    url: https://github.com/tkuchiki/alp/releases/download/{{alp_version}}/alp_linux_amd64.zip
    dest: "{{ download_path }}/alp_linux_amd64.zip"

- name: Expand alp
  unarchive: src={{ download_path }}/alp_linux_amd64.zip dest=/usr/local/bin remote_src=yes

- name: Remove alp.zip
  file: path={{ download_path }}/alp_linux_amd64.zip state=absent

- name: Install pt-query
  apt: name={{ item }}
  with_items:
    - libdbd-mysql-perl
    - libdbi-perl
    - libio-socket-ssl-perl
    - libnet-ssleay-perl

- name: Get percona source
  get_url: url={{ percona_url }} dest={{ download_path }} force=True

- name: Install percona
  apt: deb={{ download_path }}/percona-toolkit_3.0.4-1.xenial_amd64.deb

- name: Install htop
  apt: name=htop

- name: Restart nginx
  shell: |
    systemctl restart nginx
    
- name: Restart MySQL
  shell: |
    systemctl restart mysql
    
- name: restart App
  shell: |
    systemctl daemon-reload
    systemctl restart {{ APP_SERVICE_NAME }}

